apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dotnet19824githubx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dotnet19824githubx 
  name: dotnet19824githubx
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: dotnet19824githubx 
